nginxReplicaCount: 1

phpReplicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: bahmni
  nginx:
    name: crater-nginx
    tag: latest
  php:
    name: crater-php
    tag: latest

service:
  type: ClusterIP
  nginx:
    port: 80
  php:
    port: 9000

autoscaling:
  enabled: false
