version: '3'

services:
  crater-php:
    image: bahmni/crater-php
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      APP_URL: ${CRATER_APP_URL:?}
      DB_HOST: ${CRATER_DB_HOST:?}
      DB_PORT: ${CRATER_DB_PORT:?}
      DB_DATABASE: ${CRATER_DB_DATABASE:?}
      DB_USERNAME: ${CRATER_DB_USERNAME:?}
      DB_PASSWORD: ${CRATER_DB_PASSWORD:?}
      SANCTUM_STATEFUL_DOMAINS: ${CRATER_SANCTUM_STATEFUL_DOMAINS:?}
      SESSION_DOMAIN: ${CRATER_SESSION_DOMAIN:?}
      AUTO_INSTALL: ${CRATER_AUTO_INSTALL:?}
      ADMIN_NAME: ${CRATER_ADMIN_NAME:?}
      ADMIN_EMAIL: ${CRATER_ADMIN_EMAIL:?}
      ADMIN_PASSWORD: ${CRATER_ADMIN_PASSWORD:?}
      COMPANY_NAME: ${CRATER_COMPANY_NAME:?}
      COMPANY_SLUG: ${CRATER_COMPANY_SLUG:?}
      COUNTRY_ID: ${CRATER_COUNTRY_ID:?}
    networks:
      - crater

  craterdb:
    image: mysql:5.7
    restart: always
    volumes:
      - db:/var/lib/mysql
      # # If you want to persist data on the host, comment the line above this one...
      # # and uncomment the line under this one.
      # - ./docker-compose/db/data:/var/lib/mysql:rw,delegated
    environment:
      MYSQL_USER: crater
      MYSQL_PASSWORD: crater
      MYSQL_DATABASE: crater
      MYSQL_ROOT_PASSWORD: crater
    ports:
      - '33006:3306'
    networks:
      - crater

  crater-nginx:
    image: bahmni/crater-nginx
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - crater

  cron:
    build:
      context: ../
      dockerfile: docker/cron.dockerfile
    image: crater-cron
    volumes:
      - ../:/var/www
    networks:
      - crater

volumes:
  db:

networks:
  crater:
    driver: bridge
