version: '3'

services:
  crater-php:
    image: bahmni/crater-php
    restart: unless-stopped
    working_dir: /var/www/
    environment:
      APP_URL: http://crater.test
      DB_HOST: craterdb
      DB_PORT: 3306
      DB_DATABASE: crater
      DB_USERNAME: crater
      DB_PASSWORD: "crater"
      SANCTUM_STATEFUL_DOMAINS: crater.test
      SESSION_DOMAIN: crater.test
      AUTO_INSTALL: "true"
      ADMIN_EMAIL: admin@craterapp.com
      ADMIN_NAME: Jane Doe
      ADMIN_PASSWORD: "crater@123"
      COMPANY_NAME: xyz
      COMPANY_SLUG: xyz
      COUNTRY_ID: 1
    networks:
      - crater

  craterdb:
    image: mysql:5.7
    restart: always
    volumes:
      - db:/var/lib/mysql
      # # If you want to persist data on the host, comment the line above this one...
      # # and uncomment the line under this one.
      # - ./docker-compose/db/data:/var/lib/mysql:rw,delegated
    environment:
      MYSQL_USER: crater
      MYSQL_PASSWORD: crater
      MYSQL_DATABASE: crater
      MYSQL_ROOT_PASSWORD: crater
    ports:
      - '33006:3306'
    networks:
      - crater

  crater-nginx:
    image: bahmni/crater-nginx
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - crater

  cron:
    build:
      context: ../
      dockerfile: docker/cron.dockerfile
    image: crater-cron
    volumes:
      - ../:/var/www
    networks:
      - crater

volumes:
  db:

networks:
  crater:
    driver: bridge
