apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-nginx
  labels:
    app: {{ .Chart.Name }}-nginx
    environment: {{ .Values.metadata.labels.environment }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.nginxReplicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-nginx
      environment: {{ .Values.metadata.labels.environment }}
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-nginx
        environment: {{ .Values.metadata.labels.environment }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-nginx
          image: "{{ .Values.image.repository }}/{{ .Values.image.nginx.name }}:{{ .Values.image.nginx.tag }}"
          resources: {}
          ports:
            - containerPort: {{ .Values.service.nginx.port }}
              protocol: TCP
      restartPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-php
  labels:
    app: {{ .Chart.Name }}-php
    environment: {{ .Values.metadata.labels.environment }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.phpReplicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-php
      environment: {{ .Values.metadata.labels.environment }}
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-php
        environment: {{ .Values.metadata.labels.environment }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-php
          image: "{{ .Values.image.repository }}/{{ .Values.image.php.name }}:{{ .Values.image.php.tag }}"
          resources: {}
          workingDir: /var/www/
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-config
                optional: false
            - secretRef:
                name: {{.Chart.Name }}-secrets
                optional: false
      restartPolicy: Always
